# Generated by Django 5.1.3 on 2024-12-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firsr_name',
            new_name='first_name',
        ),
    ]
